name: Update dependencies

on:
  ? workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          submodules: true
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # pin@v6.0.1
        with:
          distribution: 'corretto'
          java-version: '8'
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # pin@v6.3.0
        with:
          gradle-version: 8.14.4 # Gradle 9 cannot run on Java 8
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # pin@stable
      - run: sudo apt-get install -y libpcsclite-dev
      - run: cargo install cargo-edit
      - run: cd src/test/rust/simulator && cargo upgrade && cargo update && cargo test
      - run: cd src/main/rust/cardtool && cargo upgrade && cargo update && cargo test
      # dockerimage.yml is not triggered without repo scoped token, doing testing in the task, ref. https://github.com/peter-evans/create-pull-request/issues/48
      - run: gradle build
      - run: gradle -Pjc_version=3.0.5 --console=verbose clean cap --info
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # pin@v8.1.1
        with:
          title: Update dependencies
          commit-message: Update dependencies
          delete-branch: true
